name: Smoke Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      SMOKE_BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install curl & jq
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Ensure smoke script is executable
        run: chmod +x smoke_test_api.sh

      - name: Verify SMOKE_BASE_URL is set
        run: |
          if [ -z "${SMOKE_BASE_URL}" ]; then
            echo "❌ SMOKE_BASE_URL secret is not set. Set it under Settings → Secrets → Actions."
            echo "   Go to GitHub → Settings → Secrets → Actions → New repository secret"
            echo "   Name: SMOKE_BASE_URL"
            echo "   Value: https://minigame.soulbridgeai.com"
            exit 1
          fi
          echo "Target: ${SMOKE_BASE_URL}"

      - name: Test API endpoints directly (bypass health check)
        run: |
          echo "🔍 Testing API endpoints directly since /health has auth issues..."

          # Test API ping - should return 200 with {"ok": true}
          echo "Testing /api/word-finder/_ping"
          if curl -sf "${SMOKE_BASE_URL}/api/word-finder/_ping" | grep -q '"ok":true'; then
            echo "✅ API ping working"
          else
            echo "❌ API ping failed"
            exit 1
          fi

      - name: Run smoke tests
        run: ./smoke_test_api.sh "${SMOKE_BASE_URL}"
