name: Smoke Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      SMOKE_BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install curl & jq
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Ensure smoke script is executable
        run: chmod +x smoke_test_api.sh

      - name: Verify SMOKE_BASE_URL is set
        run: |
          if [ -z "${SMOKE_BASE_URL}" ]; then
            echo "❌ SMOKE_BASE_URL secret is not set. Set it under Settings → Secrets → Actions."
            exit 1
          fi
          echo "Target: ${SMOKE_BASE_URL}"

      - name: Wait for app to be healthy
        run: |
          for i in {1..60}; do
            if curl -sf "${SMOKE_BASE_URL}/health" >/dev/null; then
              echo "✅ App is up"
              exit 0
            fi
            echo "⏳ waiting for ${SMOKE_BASE_URL}/health ..."
            sleep 2
          done
          echo "❌ App never became healthy at ${SMOKE_BASE_URL}/health"
          exit 1

      - name: Run smoke tests
        run: ./smoke_test_api.sh "${SMOKE_BASE_URL}"
